In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [15]:
zero_arr = np.zeros((3,5), float)
print(zero_arr)

zero_arr.dtype

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


dtype('float64')

In [4]:
ones_arr = np.ones((2,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [10]:
# full_arr = np.full(2, 4)
# full_arr = np.full((5, 7), 4)
# print(full_arr)

np.full((5, 7), 4)  # this will also print he array

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.arange(1, 100, abs(18))

array([ 1, 19, 37, 55, 73, 91])

In [14]:
arr1.size

4

In [19]:
# this will show error
# arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [2, 3, 5]])

np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [2, 3, 5, 10]])


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2,  3,  5, 10]])

In [28]:
# 🌟 Create a 2D NumPy array

temp_arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [2, 3, 5, 10]
])

# 🖨️ Print the original array
print("🔹 Original Array:\n", temp_arr)

# 🔻 Flatten the array to 1D
print("\n🔹 Flattened Array:\n", temp_arr.flatten())

# 🔄 Reshape to 4x3 (must have same total elements)
print("\n🔹 Reshaped Array (4x3):\n", temp_arr.reshape((4, 3)))

# 📏 Resize array to length 10 (modifies in-place, fills with zeros if needed)
temp_arr.resize((10,))  # Note: this will modify temp_arr itself
print("\n🔹 Resized Array (1D length 10):\n", temp_arr)

🔹 Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  3  5 10]]

🔹 Flattened Array:
 [ 1  2  3  4  5  6  7  8  2  3  5 10]

🔹 Reshaped Array (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  2]
 [ 3  5 10]]

🔹 Resized Array (1D length 10):
 [1 2 3 4 5 6 7 8 2 3]
