In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [4]:
arr[2, 1]

np.int64(8)

In [21]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
# arr[1] = 3
print(arr)

[[1 0 3]
 [3 0 3]
 [7 0 9]]


In [15]:
# Get all rows of the first column
first_col = arr[:, 0]
# first_col = arr[0:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [6]:
arr[1:3, 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

# 3D Arrays 

In [8]:
# 🧊 Create a 3D array: 2 "blocks", each with 2 rows and 3 columns
arr3D = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print("🔹 3D Array:\n", arr3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
print("📏 Shape:", arr3D.shape)  # (2, 2, 3)


📏 Shape: (2, 2, 3)


In [17]:
arr3D[0, 1, 1]

np.int64(5)

In [10]:
arr3D[:, 0, :]  # Get the first row from both sheets

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
print("🎯 Fancy Pick:", arr3D[[0, 1], [1, 0], [2, 1]])  
# Picks: arr3D[0,1,2] → 6 and arr3D[1,0,1] → 8


🎯 Fancy Pick: [6 8]
