In [1]:
import numpy as np 

In [4]:
# 🌟 Create a 2D NumPy array
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [2, 3, 5, 10]
])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  3  5 10]]


In [5]:
print(arr[0])

[1 2 3 4]


In [6]:
print(arr[-1])

[ 2  3  5 10]


In [8]:
print(arr[1:5])

[[ 5  6  7  8]
 [ 2  3  5 10]]


In [10]:
print(arr[2:])

[[ 2  3  5 10]]


In [12]:
print(arr[:5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  3  5 10]]


In [21]:
# This is not a copy here, even assigned a new variable 
# so if val changed in the original, it will affect the new one and vice versa

flat_arr = arr[0:1]
print(flat_arr)

[[1 2 3 4]]


In [24]:
# here to make a copy

copy_arr = arr[0: 2].copy()
print(copy_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
random_arr = np.random.randint(1, 100, 10)

print(random_arr)

#  here its the index we wjhat to print
print(random_arr[[1, 5, 6]])

[70 11 69 40 97  3  2 50 29 29]
[11  3  2]


In [32]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


# Assignment starts here

In [34]:
# 🎲 Generate a 2D array of random integers between 3 (inclusive) and 10 (exclusive)
random_2d = np.random.randint(3, 10, size=(3, 4))  # Shape = 3 rows, 4 columns

print("🔹 2D Random Integer Array:\n", random_2d)


🔹 2D Random Integer Array:
 [[4 5 9 5]
 [8 6 5 3]
 [7 7 5 5]]


In [44]:
random_2d.shape

(3, 4)

In [45]:
random_2d[[0, 1], [2, 2]]

array([9, 5], dtype=int32)

In [48]:
random_2d[random_2d > 5]

array([9, 8, 6, 7, 7], dtype=int32)

In [52]:
one_d_arr = np.random.randint(1, 100, 9)
print(one_d_arr)

[41 40 82 30 10 62 91 10 60]


In [53]:
one_d_arr.reshape((3,3))

array([[41, 40, 82],
       [30, 10, 62],
       [91, 10, 60]], dtype=int32)