In [1]:
import numpy as np
import sys

In [3]:
np_arr = np.array(range(10, 100))

In [4]:
np_arr.shape

(90,)

In [5]:
list_data = list(range(100000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 80005600000 bytes
NumPy array size: 800000 bytes


In [6]:
line_space = np.linspace(0, 5, 5)

In [7]:
print(line_space)

[0.   1.25 2.5  3.75 5.  ]


In [8]:
np_arr.ndim

1

In [9]:
np_arr.dtype

dtype('int64')

In [10]:
np_arr_float = np_arr.astype(np.float32)
print(np_arr_float)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63.
 64. 65. 66. 67. 68. 69. 70. 71. 72. 73. 74. 75. 76. 77. 78. 79. 80. 81.
 82. 83. 84. 85. 86. 87. 88. 89. 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [12]:
reshaped = arr.reshape((3, 2)) # Change shape
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
print(arr[arr > 5])

[6]


In [14]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
print(arr[[0, 1], [2]])

[3 6]


In [16]:
arr_2 = np.array(range(1,6))

In [17]:
print(arr[arr % 2 == 0])

[2 4 6]


In [18]:
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [19]:
print(np.sum(arr, axis=0)) # Sum along rows (down each column)
print(np.sum(arr, axis=1)) # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [20]:
first_col = arr[:, 0]
print(first_col) # Output: [1 4 7]

[1 4 7]


In [21]:
A = np.ones((3,2))
B = np.ones((4,2))

In [24]:
print(A)
print("-----------------")
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
-----------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
print(A + B)

ValueError: operands could not be broadcast together with shapes (3,2) (4,2) 

In [32]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [27]:
print(mean)

[20. 30. 40.]


In [29]:
print(std)

[7.07106781 7.07106781 7.07106781]


In [31]:
(data - mean)

array([[-10., -10., -10.],
       [ -5.,  -5.,  -5.],
       [  0.,   0.,   0.],
       [  5.,   5.,   5.],
       [ 10.,  10.,  10.]])

In [3]:
arr = np.array([1, 2, 3])
padded = np.pad(arr, (2, 3), mode='constant', constant_values=0)
print(padded)

[0 0 1 2 3 0 0 0]


In [8]:
arr = np.array([[1, 2],
                [3, 4]])

padded = np.pad(arr, ((2, 2), (1, 1)), mode='constant', constant_values=9)
print(padded)


[[9 9 9 9]
 [9 9 9 9]
 [9 1 2 9]
 [9 3 4 9]
 [9 9 9 9]
 [9 9 9 9]]


In [4]:
rg = np.random.default_rng()

In [14]:
r = np.floor(10 * rg.random((3, 4)))
r

array([[7., 8., 7., 0.],
       [2., 2., 9., 9.],
       [4., 2., 5., 6.]])

In [2]:
arr = np.array([10, 20, 30, 40, 50])

In [3]:
view  = arr[1:4]

In [5]:
view[0] = 999

In [6]:
view

array([999,  30,  40])

In [7]:
arr

array([ 10, 999,  30,  40,  50])

In [8]:
mat = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])

In [17]:
mat[ [1, 2], [2, 3] ] 
"""
First array → row indices [1, 2]

Second array → col indices [2, 3]

NumPy pairs them elementwise.
"""

array([ 7, 12])

In [10]:
mat[::, ::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [11]:
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [15]:
mat[[0,2], :]       # → rows 0 and 2
mat[:, [0,2]]       # → cols 0 and 2


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [12]:
cube = np.array([ [[1,2,3],
                   [4,5,6]],
                  
                  [[7,8,9],
                   [10,11,12]] ])

# cube.shape → (2,2,3)


In [13]:
cube[0, 0, 1]   # 2   (block 0, row 0, col 1)
cube[1, 1, 2]   # 12  (block 1, row 1, col 2)
cube[:, 0, 2]   # [3, 9] → take col 2 from row 0 in all blocks


array([3, 9])

In [14]:
cube[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [19]:
arr = np.array([3, 6, 9, 12, 15, 18])

# 👉 Write a boolean indexing expression to select all elements 
#  that are multiples of 3 but greater than 10.

arr[(arr % 3 == 0) & (arr > 10)]

array([12, 15, 18])

In [24]:
data = np.array([(1, 'Alice', 25),
                 (2, 'Bob', 30),
                 (3, 'Charlie', 22)],
                dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])


In [25]:
data['name']

array(['Alice', 'Bob', 'Charlie'], dtype='<U10')

In [26]:
data[data['age'] > 23]

array([(1, 'Alice', 25), (2, 'Bob', 30)],
      dtype=[('id', '<i4'), ('name', '<U10'), ('age', '<i4')])

In [28]:
data[data['age'] > 23]['name']

array(['Alice', 'Bob'], dtype='<U10')

In [34]:
data[(data['name'] == 'Alice') | (data['name'] == 'Charlie')]['age']
# → [25, 22]


#  ✨ Even cleaner (using np.isin):
data[np.isin(data['name'], ['Alice', 'Charlie'])]['age']

array([25, 22], dtype=int32)

In [ ]:
arr = np.arange(1, 10).reshape(3,3)
# Using vectorized operations only, how would you double 
# all odd numbers but leave even numbers unchanged?



In [35]:
arr[arr % 2 != 0]  * 2

array([ 6, 18, 30])

In [2]:
# The first 12 square numbers
a = np.arange(12)**2 
# a is array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

# An array of indices (our "shopping list")
i = np.array([1, 1, 3, 8, 5])

In [3]:
a[i]

array([ 1,  1,  9, 64, 25])

In [4]:
# Same 'a' as before
a = np.array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

# A 2D array of indices
j = np.array([[3, 4], 
              [9, 7]])

In [5]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [13]:
a = np.arange(12).reshape(3, 4)

i = np.array([[0, 1], [1, 2]])

j = np.array([[2, 1], [3, 3]])

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [15]:
a[j]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [16]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [21]:
a = np.arange(12).reshape(3, 4)
# a is:
# [[ 0,  1,  2,  3],
#  [ 4,  5,  6,  7],
#  [ 8,  9, 10, 11]]

b = a > 4

In [22]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [24]:
b1 = np.array([False, True, False]) # for rows

In [28]:
b2 = np.array([True, False, True, False]) # for columns

In [31]:
print(a[b1])
print("\n-----------------\n")
print(a[:, b2])

[[4 5 6 7]]

-----------------

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [32]:
a = np.array([2, 3, 4, 5])      # Length is 4
b = np.array([8, 5, 4])        # Length is 3
c = np.array([5, 4, 6, 8, 3])  # Length is 5

ax, bx, cx = np.ix_(a, b, c)

In [33]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [34]:
bx

array([[[8],
        [5],
        [4]]])

In [40]:
result = (ax + bx) * cx

In [41]:
result

array([[[ 50,  40,  60,  80,  30],
        [ 35,  28,  42,  56,  21],
        [ 30,  24,  36,  48,  18]],

       [[ 55,  44,  66,  88,  33],
        [ 40,  32,  48,  64,  24],
        [ 35,  28,  42,  56,  21]],

       [[ 60,  48,  72,  96,  36],
        [ 45,  36,  54,  72,  27],
        [ 40,  32,  48,  64,  24]],

       [[ 65,  52,  78, 104,  39],
        [ 50,  40,  60,  80,  30],
        [ 45,  36,  54,  72,  27]]])

In [42]:
result[3, 2, 4]

np.int64(27)

In [43]:
a[3] + b[2] * c[4]

np.int64(17)

In [44]:
ax + bx

array([[[10],
        [ 7],
        [ 6]],

       [[11],
        [ 8],
        [ 7]],

       [[12],
        [ 9],
        [ 8]],

       [[13],
        [10],
        [ 9]]])

In [45]:
time = np.linspace(20, 145, 5)  # time scale

In [46]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [49]:
a = np.arange(5)
print("A before")
print(a)
a[[0, 0, 2]] += 1
print("\nA after")
a

A before
[0 1 2 3 4]

A after


array([1, 1, 3, 3, 4])

In [55]:
A = np.array([[1, 2],
              [3, 4]])
np.tile(A, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])